### ISSUE TITLE
Python 3.10 builds

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/awscli-feedstock#974]
Would be nice to see packages for python 3.10.

**Comment by tkelman** [comment]
https://conda-forge.org/status/ shows it as not solvable. Not sure exactly which dependency is the problem here:
`awscli (4) Error: not solvable (bot CI job): master: ['linux_64_python3.10.____cpython: Encountered problems while solving:\n - package python_abi-3.10-2_cp310 requires python 3.10.*, but none of the providers can be installed\n', 'linux_aarch64_python3.10.____cpython: Encountered problems while solving:\n - nothing provides openssl >=1.0.2p,<1.0.3a needed by python-3.7.1-hd75c258_1001\n', 'linux_ppc64le_python3.10.____cpython: Encountered problems while solving:\n - package python_abi-3.10-2_cp310 requires python 3.10.*, but none of the providers can be installed\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\n - package pyyaml-3.12-py27ha7932d0_1 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\n - package pyyaml-5.4.1-py38h1a28f6b_1 requires python >=3.8,<3.9.0a0, but none of the providers can be installed\n', 'win_64_python3.10.____cpython: Encountered problems while solving:\n - nothing provides vc 10.* needed by python-3.4.5-0\n']
Immediate Children: aws-shell, caper, cfncluster, sregistry`

**Comment by analog-cbarber** [comment]
The recipe has max versions:

```yaml
run:
    - python
#    - python >=3.6
    - botocore =={{ botocore_pin }}
    - colorama >=0.2.5,<0.4.4
    - docutils >=0.10,<0.16
    - rsa >=3.1.2,<4.8
    - s3transfer >=0.5.0,<0.6.0
    - pyyaml >=3.10,<5.5
```

It appears that pyyaml does not support 3.10 until version 6.0. I don't think there are any breaking changes on pyyaml, so there probably isn't a specific reason for that limit.

**Comment by tkelman** [comment]
guess we'll need https://github.com/aws/aws-cli/pull/6648 to get merged upstream

**Comment by tkelman** [comment]
Not sure what changed wrt pyyaml, but I guess #1096 resolved this?
